### ISSUE TITLE
[noob-question] how to process the input from readline once its been obtained from the user

### ISSUE THREAD

**Issue by vxe** [vindarel/cl-readline-example#2]
I see `setf` the value `text`

```
      (setf text
            (rl:readline :prompt (format nil "[~a]> " i)
                         :add-history t
                         :novelty-check #'novelty-check))
```

but I'm not sure how to access `text` after the readline process, I have tried doing it after and it perhaps unsurprisingly says variable is undefined.  thanks

**Comment by vindarel** [comment]
Hi, maybe you wanted to use `text` outside of the `do` loop or you made a typo?

I commited a simple example.

```lisp
        (setf text
              (rl:readline :prompt (format nil "cl-readline ~a> " i)
                           :add-history t
                           :novelty-check #'novelty-check))
        (echo text))
```

**Comment by vxe** [comment]
wow yeah typo on my part looks like it works as intended, closing
